from django.core.management.base import BaseCommand
from complaints.models import District, PradeshiyaSabha, Wasama


class Command(BaseCommand):
    help = 'Populates ALL Sri Lanka districts and Pradeshiya Sabhas into the database.'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('=' * 60))
        self.stdout.write(self.style.SUCCESS('Populating All Sri Lanka Location Data'))
        self.stdout.write(self.style.SUCCESS('=' * 60))

        # Full Sri Lanka data: District -> [Pradeshiya Sabhas]
        # Source: Department of Local Government, Sri Lanka
        data = {
            'Colombo': [
                'Colombo Municipal Council',
                'Sri Jayawardenepura Kotte Municipal Council',
                'Dehiwala-Mount Lavinia Municipal Council',
                'Moratuwa Municipal Council',
                'Kaduwela Municipal Council',
                'Homagama Municipal Council',
                'Maharagama Urban Council',
                'Kolonnawa Urban Council',
                'Kesbewa Urban Council',
                'Seethawaka Pradeshiya Sabha',
                'Padukka Pradeshiya Sabha',
            ],
            'Gampaha': [
                'Gampaha Municipal Council',
                'Negombo Municipal Council',
                'Kelaniya Municipal Council',
                'Wattala-Mabole Urban Council',
                'Ja-Ela Urban Council',
                'Katana Pradeshiya Sabha',
                'Mahara Pradeshiya Sabha',
                'Minuwangoda Pradeshiya Sabha',
                'Attanagalla Pradeshiya Sabha',
                'Biyagama Pradeshiya Sabha',
                'Divulapitiya Pradeshiya Sabha',
                'Dompe Pradeshiya Sabha',
                'Gampaha Pradeshiya Sabha',
                'Mirigama Pradeshiya Sabha',
                'Wattala Pradeshiya Sabha',
            ],
            'Kalutara': [
                'Kalutara Urban Council',
                'Panadura Urban Council',
                'Beruwala Pradeshiya Sabha',
                'Bandaragama Pradeshiya Sabha',
                'Bulathsinhala Pradeshiya Sabha',
                'Dodangoda Pradeshiya Sabha',
                'Horana Pradeshiya Sabha',
                'Ingiriya Pradeshiya Sabha',
                'Kalutara Pradeshiya Sabha',
                'Madurawela Pradeshiya Sabha',
                'Mathugama Pradeshiya Sabha',
                'Millaniya Pradeshiya Sabha',
                'Palindanuwara Pradeshiya Sabha',
                'Walallawita Pradeshiya Sabha',
            ],
            'Kandy': [
                'Kandy Municipal Council',
                'Gampola Urban Council',
                'Nawalapitiya Urban Council',
                'Akurana Pradeshiya Sabha',
                'Delthota Pradeshiya Sabha',
                'Doluwa Pradeshiya Sabha',
                'Ganga Ihala Korale Pradeshiya Sabha',
                'Harispattuwa Pradeshiya Sabha',
                'Hatharaliyadda Pradeshiya Sabha',
                'Kundasale Pradeshiya Sabha',
                'Medadumbara Pradeshiya Sabha',
                'Minipe Pradeshiya Sabha',
                'Panvila Pradeshiya Sabha',
                'Pasbage Korale Pradeshiya Sabha',
                'Pathadumbara Pradeshiya Sabha',
                'Pathahewaheta Pradeshiya Sabha',
                'Poojapitiya Pradeshiya Sabha',
                'Thumpane Pradeshiya Sabha',
                'Udadumbara Pradeshiya Sabha',
                'Udapalatha Pradeshiya Sabha',
                'Udunuwara Pradeshiya Sabha',
                'Ududumbara Pradeshiya Sabha',
                'Yatinuwara Pradeshiya Sabha',
            ],
            'Matale': [
                'Matale Urban Council',
                'Dambulla Urban Council',
                'Ambanganga Korale Pradeshiya Sabha',
                'Dambulla Pradeshiya Sabha',
                'Galewela Pradeshiya Sabha',
                'Laggala-Pallegama Pradeshiya Sabha',
                'Matale Pradeshiya Sabha',
                'Naula Pradeshiya Sabha',
                'Pallepola Pradeshiya Sabha',
                'Rattota Pradeshiya Sabha',
                'Ukuwela Pradeshiya Sabha',
                'Wilgamuwa Pradeshiya Sabha',
                'Yatawatta Pradeshiya Sabha',
            ],
            'Nuwara Eliya': [
                'Nuwara Eliya Urban Council',
                'Hatton-Dickoya Urban Council',
                'Talawakele-Lindula Urban Council',
                'Ambagamuwa Pradeshiya Sabha',
                'Hanguranketha Pradeshiya Sabha',
                'Kotmale Pradeshiya Sabha',
                'Nuwara Eliya Pradeshiya Sabha',
                'Walapane Pradeshiya Sabha',
            ],
            'Galle': [
                'Galle Municipal Council',
                'Ambalangoda Urban Council',
                'Elpitiya Pradeshiya Sabha',
                'Akmeemana Pradeshiya Sabha',
                'Baddegama Pradeshiya Sabha',
                'Balapitiya Pradeshiya Sabha',
                'Benthota Pradeshiya Sabha',
                'Bope-Poddala Pradeshiya Sabha',
                'Galle Four Gravets Pradeshiya Sabha',
                'Gonapinuwala Pradeshiya Sabha',
                'Habaraduwa Pradeshiya Sabha',
                'Hikkaduwa Pradeshiya Sabha',
                'Imaduwa Pradeshiya Sabha',
                'Karandeniya Pradeshiya Sabha',
                'Nagoda Pradeshiya Sabha',
                'Neluwa Pradeshiya Sabha',
                'Niyagama Pradeshiya Sabha',
                'Poddala Pradeshiya Sabha',
                'Welivitiya-Divithura Pradeshiya Sabha',
                'West Hapitigam Pradeshiya Sabha',
                'Yakkalamulla Pradeshiya Sabha',
            ],
            'Matara': [
                'Matara Municipal Council',
                'Weligama Urban Council',
                'Akuressa Pradeshiya Sabha',
                'Athuraliya Pradeshiya Sabha',
                'Devinuwara Pradeshiya Sabha',
                'Dickwella Pradeshiya Sabha',
                'Hakmana Pradeshiya Sabha',
                'Kamburupitiya Pradeshiya Sabha',
                'Kirinda Puhulwella Pradeshiya Sabha',
                'Kotapola Pradeshiya Sabha',
                'Malimbada Pradeshiya Sabha',
                'Matara Pradeshiya Sabha',
                'Mulatiyana Pradeshiya Sabha',
                'Pasgoda Pradeshiya Sabha',
                'Pitabeddara Pradeshiya Sabha',
                'Thihagoda Pradeshiya Sabha',
                'Weligama Pradeshiya Sabha',
                'Welipitiya Pradeshiya Sabha',
            ],
            'Hambantota': [
                'Hambantota Urban Council',
                'Tangalle Urban Council',
                'Ambalantota Pradeshiya Sabha',
                'Angunakolapelessa Pradeshiya Sabha',
                'Beliatta Pradeshiya Sabha',
                'Hambantota Pradeshiya Sabha',
                'Katuwana Pradeshiya Sabha',
                'Lunugamvehera Pradeshiya Sabha',
                'Okewela Pradeshiya Sabha',
                'Sooriyawewa Pradeshiya Sabha',
                'Tangalle Pradeshiya Sabha',
                'Tissamaharama Pradeshiya Sabha',
                'Weeraketiya Pradeshiya Sabha',
                'Weerawila Pradeshiya Sabha',
            ],
            'Jaffna': [
                'Jaffna Municipal Council',
                'Chavakachcheri Urban Council',
                'Point Pedro Urban Council',
                'Chankanai Pradeshiya Sabha',
                'Delft Pradeshiya Sabha',
                'Island North Pradeshiya Sabha',
                'Island South Pradeshiya Sabha',
                'Jaffna Pradeshiya Sabha',
                'Karainagar Pradeshiya Sabha',
                'Nallur Pradeshiya Sabha',
                'Thenmaradchy Pradeshiya Sabha',
                'Vadamaradchy East Pradeshiya Sabha',
                'Vadamaradchy North Pradeshiya Sabha',
                'Valikamam East Pradeshiya Sabha',
                'Valikamam North Pradeshiya Sabha',
                'Valikamam South-East Pradeshiya Sabha',
                'Valikamam West Pradeshiya Sabha',
            ],
            'Kilinochchi': [
                'Kilinochchi Urban Council',
                'Kandavalai Pradeshiya Sabha',
                'Karachchi Pradeshiya Sabha',
                'Pachchilaipalli Pradeshiya Sabha',
                'Poonakary Pradeshiya Sabha',
            ],
            'Mannar': [
                'Mannar Urban Council',
                'Madhu Pradeshiya Sabha',
                'Mannar Pradeshiya Sabha',
                'Manthai West Pradeshiya Sabha',
                'Musalai Pradeshiya Sabha',
                'Nanattan Pradeshiya Sabha',
            ],
            'Mullaitivu': [
                'Maritimepattu Pradeshiya Sabha',
                'Oddusuddan Pradeshiya Sabha',
                'Puthukudiyiruppu Pradeshiya Sabha',
                'Thunukkai Pradeshiya Sabha',
                'Welioya Pradeshiya Sabha',
            ],
            'Vavuniya': [
                'Vavuniya Urban Council',
                'Vavuniya North Pradeshiya Sabha',
                'Vavuniya South Pradeshiya Sabha',
                'Vengalacheddikulam Pradeshiya Sabha',
            ],
            'Trincomalee': [
                'Trincomalee Urban Council',
                'Echchilampattai Pradeshiya Sabha',
                'Gomarankadawala Pradeshiya Sabha',
                'Kantalai Pradeshiya Sabha',
                'Kinniya Pradeshiya Sabha',
                'Kuchchaveli Pradeshiya Sabha',
                'Morawewa Pradeshiya Sabha',
                'Muttur Pradeshiya Sabha',
                'Padavi Sripura Pradeshiya Sabha',
                'Seruwila Pradeshiya Sabha',
                'Thambalagamuwa Pradeshiya Sabha',
                'Trincomalee Pradeshiya Sabha',
                'Verugal Pradeshiya Sabha',
            ],
            'Batticaloa': [
                'Batticaloa Urban Council',
                'Kattankudy Urban Council',
                'Valachchenai Urban Council',
                'Eravur Pattu Pradeshiya Sabha',
                'Eravur Town Pradeshiya Sabha',
                'Kattankudy Pradeshiya Sabha',
                'Koralai Pattu Pradeshiya Sabha',
                'Koralai Pattu Central Pradeshiya Sabha',
                'Koralai Pattu North Pradeshiya Sabha',
                'Koralai Pattu West Pradeshiya Sabha',
                'Manmunai North Pradeshiya Sabha',
                'Manmunai Pattu Pradeshiya Sabha',
                'Manmunai South and Eruvil Pattu Pradeshiya Sabha',
                'Manmunai West Pradeshiya Sabha',
                'Porativu Pattu Pradeshiya Sabha',
            ],
            'Ampara': [
                'Ampara Urban Council',
                'Kalmunai Municipal Council',
                'Akkaraipattu Urban Council',
                'Sainthamaruthu Urban Council',
                'Addalaichenai Pradeshiya Sabha',
                'Akkaraipattu Pradeshiya Sabha',
                'Ampara Pradeshiya Sabha',
                'Alayadivembu Pradeshiya Sabha',
                'Damana Pradeshiya Sabha',
                'Dehiattakandiya Pradeshiya Sabha',
                'Irakkamam Pradeshiya Sabha',
                'Kalmunai Pradeshiya Sabha',
                'Karaitivu Pradeshiya Sabha',
                'Lahugala Pradeshiya Sabha',
                'Mahaoya Pradeshiya Sabha',
                'Navithanveli Pradeshiya Sabha',
                'Ninthavur Pradeshiya Sabha',
                'Padiyathalawa Pradeshiya Sabha',
                'Pothuvil Pradeshiya Sabha',
                'Samanthurai Pradeshiya Sabha',
                'Thirukkovil Pradeshiya Sabha',
                'Uhana Pradeshiya Sabha',
            ],
            'Kurunegala': [
                'Kurunegala Municipal Council',
                'Kuliyapitiya Urban Council',
                'Pannala Urban Council',
                'Wariyapola Urban Council',
                'Alawwa Pradeshiya Sabha',
                'Ambanpola Pradeshiya Sabha',
                'Bamunakotuwa Pradeshiya Sabha',
                'Bingiriya Pradeshiya Sabha',
                'Dodangaslanda Pradeshiya Sabha',
                'Ehetuwewa Pradeshiya Sabha',
                'Galgamuwa Pradeshiya Sabha',
                'Giribawa Pradeshiya Sabha',
                'Ibbagamuwa Pradeshiya Sabha',
                'Katugampola Pradeshiya Sabha',
                'Kotavehera Pradeshiya Sabha',
                'Kuliyapitiya East Pradeshiya Sabha',
                'Kuliyapitiya West Pradeshiya Sabha',
                'Kurunegala Pradeshiya Sabha',
                'Maspotha Pradeshiya Sabha',
                'Mawathagama Pradeshiya Sabha',
                'Narammala Pradeshiya Sabha',
                'Nikaweratiya Pradeshiya Sabha',
                'Pannala Pradeshiya Sabha',
                'Polpithigama Pradeshiya Sabha',
                'Rasnayakapura Pradeshiya Sabha',
                'Rideegama Pradeshiya Sabha',
                'Udubaddawa Pradeshiya Sabha',
                'Weerambugedara Pradeshiya Sabha',
                'Wehigama Pradeshiya Sabha',
            ],
            'Puttalam': [
                'Puttalam Urban Council',
                'Chilaw Urban Council',
                'Wennappuwa Urban Council',
                'Anamaduwa Pradeshiya Sabha',
                'Arachchikattuwa Pradeshiya Sabha',
                'Chilaw Pradeshiya Sabha',
                'Dankotuwa Pradeshiya Sabha',
                'Eluwankulama Pradeshiya Sabha',
                'Kalpitiya Pradeshiya Sabha',
                'Karuwalagaswewa Pradeshiya Sabha',
                'Kobeigane Pradeshiya Sabha',
                'Mahakumbukkadawala Pradeshiya Sabha',
                'Mahawewa Pradeshiya Sabha',
                'Mundel Pradeshiya Sabha',
                'Nattandiya Pradeshiya Sabha',
                'Nawagattegama Pradeshiya Sabha',
                'Pallama Pradeshiya Sabha',
                'Puttalam Pradeshiya Sabha',
                'Vanathavilluwa Pradeshiya Sabha',
                'Wennappuwa Pradeshiya Sabha',
            ],
            'Anuradhapura': [
                'Anuradhapura Municipal Council',
                'Galenbindunuwewa Pradeshiya Sabha',
                'Horowpothana Pradeshiya Sabha',
                'Ipalogama Pradeshiya Sabha',
                'Kahatagasdigiliya Pradeshiya Sabha',
                'Kebithigollewa Pradeshiya Sabha',
                'Kekirawa Pradeshiya Sabha',
                'Mahavilachchiya Pradeshiya Sabha',
                'Medawachchiya Pradeshiya Sabha',
                'Mihinthale Pradeshiya Sabha',
                'Nachchadoowa Pradeshiya Sabha',
                'Nochchiyagama Pradeshiya Sabha',
                'Nuwaragam Palatha Central Pradeshiya Sabha',
                'Nuwaragam Palatha East Pradeshiya Sabha',
                'Padaviya Pradeshiya Sabha',
                'Palagala Pradeshiya Sabha',
                'Palugaswewa Pradeshiya Sabha',
                'Rajanganaya Pradeshiya Sabha',
                'Rambewa Pradeshiya Sabha',
                'Thalawa Pradeshiya Sabha',
                'Thambuttegama Pradeshiya Sabha',
                'Thirappane Pradeshiya Sabha',
            ],
            'Polonnaruwa': [
                'Polonnaruwa Urban Council',
                'Medirigiriya Pradeshiya Sabha',
                'Dimbulagala Pradeshiya Sabha',
                'Elahera Pradeshiya Sabha',
                'Hingurakgoda Pradeshiya Sabha',
                'Lankapura Pradeshiya Sabha',
                'Polonnaruwa Pradeshiya Sabha',
                'Thamankaduwa Pradeshiya Sabha',
                'Welikanda Pradeshiya Sabha',
            ],
            'Badulla': [
                'Badulla Urban Council',
                'Bandarawela Urban Council',
                'Haputale Urban Council',
                'Welimada Urban Council',
                'Badulla Pradeshiya Sabha',
                'Ella Pradeshiya Sabha',
                'Haldummulla Pradeshiya Sabha',
                'Hali-Ela Pradeshiya Sabha',
                'Kandaketiya Pradeshiya Sabha',
                'Lunugala Pradeshiya Sabha',
                'Mahiyanganaya Pradeshiya Sabha',
                'Meegahakivula Pradeshiya Sabha',
                'Passara Pradeshiya Sabha',
                'Ridimaliyadda Pradeshiya Sabha',
                'Soranathota Pradeshiya Sabha',
                'Uva Paranagama Pradeshiya Sabha',
                'Welimada Pradeshiya Sabha',
            ],
            'Monaragala': [
                'Monaragala Urban Council',
                'Bibile Urban Council',
                'Badalkumbura Pradeshiya Sabha',
                'Bibile Pradeshiya Sabha',
                'Buttala Pradeshiya Sabha',
                'Katharagama Pradeshiya Sabha',
                'Medagama Pradeshiya Sabha',
                'Monaragala Pradeshiya Sabha',
                'Sevanagala Pradeshiya Sabha',
                'Siyambalanduwa Pradeshiya Sabha',
                'Thanamalvila Pradeshiya Sabha',
                'Wellawaya Pradeshiya Sabha',
            ],
            'Ratnapura': [
                'Ratnapura Municipal Council',
                'Embilipitiya Urban Council',
                'Balangoda Urban Council',
                'Ayagama Pradeshiya Sabha',
                'Balangoda Pradeshiya Sabha',
                'Eheliyagoda Pradeshiya Sabha',
                'Embilipitiya Pradeshiya Sabha',
                'Godakawela Pradeshiya Sabha',
                'Imbulpe Pradeshiya Sabha',
                'Kalawana Pradeshiya Sabha',
                'Kiriella Pradeshiya Sabha',
                'Kolonna Pradeshiya Sabha',
                'Kuruwita Pradeshiya Sabha',
                'Nivitigala Pradeshiya Sabha',
                'Opanayaka Pradeshiya Sabha',
                'Palmadulla Pradeshiya Sabha',
                'Ratnapura Pradeshiya Sabha',
                'Weligepola Pradeshiya Sabha',
            ],
            'Kegalle': [
                'Kegalle Urban Council',
                'Mawanella Urban Council',
                'Aranayaka Pradeshiya Sabha',
                'Bulathkohupitiya Pradeshiya Sabha',
                'Dehiovita Pradeshiya Sabha',
                'Deraniyagala Pradeshiya Sabha',
                'Galigamuwa Pradeshiya Sabha',
                'Kegalle Pradeshiya Sabha',
                'Mawanella Pradeshiya Sabha',
                'Rambukkana Pradeshiya Sabha',
                'Ruwanwella Pradeshiya Sabha',
                'Warakapola Pradeshiya Sabha',
                'Yatiyanthota Pradeshiya Sabha',
            ],
        }

        total_districts_created = 0
        total_districts_skipped = 0
        total_sabhas_created = 0
        total_sabhas_skipped = 0

        for district_name, sabha_list in data.items():
            self.stdout.write(f'\n[District] {district_name}')
            district, created = District.objects.get_or_create(name=district_name)
            if created:
                total_districts_created += 1
                self.stdout.write(self.style.SUCCESS(f'   [NEW] District created: {district_name}'))
            else:
                total_districts_skipped += 1
                self.stdout.write(self.style.WARNING(f'   [EXISTS] District found: {district_name}'))

            for sabha_name in sabha_list:
                sabha, created = PradeshiyaSabha.objects.get_or_create(
                    name=sabha_name,
                    district=district
                )
                if created:
                    total_sabhas_created += 1
                    self.stdout.write(self.style.SUCCESS(f'      [OK] Created: {sabha_name}'))
                else:
                    total_sabhas_skipped += 1
                    self.stdout.write(f'      - Exists:  {sabha_name}')

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS('=' * 60))
        self.stdout.write(self.style.SUCCESS('[DONE] Population Complete!'))
        self.stdout.write(self.style.SUCCESS(
            f'   Districts  : {total_districts_created} created, {total_districts_skipped} already existed'
        ))
        self.stdout.write(self.style.SUCCESS(
            f'   Local Bodies: {total_sabhas_created} created, {total_sabhas_skipped} already existed'
        ))
        self.stdout.write(self.style.SUCCESS('=' * 60))
