# Generated by Django 6.0.7 on 2026-07-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('citizen_name', models.CharField(max_length=150)),
                ('citizen_email', models.EmailField(max_length=254)),
                ('citizen_phone', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('ROAD_DAMAGE', 'Road Damage (මාර්ග හානි)'), ('WASTE_MGMT', 'Waste Management (කසළ කළමනාකරණය)'), ('DRAINAGE', 'Drainage Issues (කාණු පද්ධති ගැටළු)'), ('STREET_LIGHT', 'Street Lighting (විදුලි පහන් ගැටළු)'), ('ENVIRONMENT', 'Environmental Concerns (පරිසර ගැටළු)'), ('PUBLIC_SVC', 'Public Services (පොදු සේවා)'), ('OTHER', 'Other (වෙනත්)')], default='OTHER', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='complaint_evidence/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (නොවිසඳුනු)'), ('IN_PROGRESS', 'In Progress (ක්\u200dරියාත්මක වෙමින් පවතින)'), ('RESOLVED', 'Resolved (විසඳන ලද)'), ('REJECTED', 'Rejected (ප්\u200dරතික්ෂේප කරන ලද)')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('status_from', models.CharField(max_length=20)),
                ('status_to', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='complaints.complaint')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.district'),
        ),
        migrations.CreateModel(
            name='PradeshiyaSabha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabhas', to='complaints.district')),
            ],
            options={
                'verbose_name': 'Pradeshiya Sabha',
                'verbose_name_plural': 'Pradeshiya Sabhas',
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='pradeshiya_sabha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.pradeshiyasabha'),
        ),
        migrations.CreateModel(
            name='Wasama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Grama Niladhari Division Code, e.g. GN 600', max_length=50)),
                ('pradeshiya_sabha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasamas', to='complaints.pradeshiyasabha')),
            ],
            options={
                'verbose_name': 'Wasama',
                'verbose_name_plural': 'Wasamas',
                'unique_together': {('name', 'pradeshiya_sabha')},
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OFFICER', 'Officer'), ('ADMIN', 'Administrator')], default='OFFICER', max_length=20)),
                ('assigned_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='complaints.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_pradeshiya_sabha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='complaints.pradeshiyasabha')),
                ('assigned_wasama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='complaints.wasama')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='wasama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.wasama'),
        ),
    ]
