# Generated by Django 6.0.5 on 2026-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('WATER_SUPPLY', 'Water Supply Issues'), ('IRRIGATION', 'Irrigation Issues'), ('ROAD_BRIDGE_DAMAGE', 'Road & Bridge Damage'), ('WASTE_MGMT', 'Waste Management Issues'), ('ELECTRICITY_SUPPLY', 'Electricity Supply Issues'), ('DRAINAGE_FLOOD', 'Drainage & Flood Issues'), ('LAND_ISSUES', 'Land Issues'), ('HOUSING_ISSUES', 'Housing Issues'), ('HEALTHCARE_SHORTAGE', 'Healthcare Shortages'), ('EDUCATION_FACILITIES', 'School & Educational Facility Shortages'), ('TRANSPORT_ISSUES', 'Transport Issues'), ('EMPLOYMENT_ISSUES', 'Employment Shortages'), ('AGRICULTURE_ISSUES', 'Agricultural Issues'), ('WILDLIFE_CONFLICT', 'Human-Wildlife Conflict (Elephants, Monkeys, etc.)'), ('ENVIRONMENT_POLLUTION', 'Environmental Pollution'), ('ILLEGAL_MINING_LOGGING', 'Illegal Sand, Stone & Timber Mining'), ('NARCOTICS_CRIME', 'Narcotics & Crime'), ('NOISE_POLLUTION', 'Noise Pollution'), ('STREET_LIGHTING', 'Faulty Street Lighting'), ('PUBLIC_SAFETY', 'Public Safety Issues'), ('MARKET_COST_LIVING', 'Market & Cost of Living Issues'), ('CORRUPTION_IRREGULARITIES', 'Irregularities & Corruption'), ('PUBLIC_LAND_ENCROACHMENT', 'Encroachment of Public Lands'), ('STRAY_ANIMALS', 'Animal Waste & Stray Animals Issues'), ('TELECOM_INTERNET', 'Internet & Telecom Service Issues'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
